/**
 * RetailMetrics Mock API Server
 * 
 * A simple Express server that provides mock API endpoints for the RetailMetrics dashboard.
 * This uses the data generated by mockDataGenerator.js and serves it via REST endpoints.
 */

const express = require('express');
const cors = require('cors');
const mockData = require('./data');

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());

// Add some request logging
app.use((req, res, next) => {
  console.log(`${new Date().toISOString()} - ${req.method} ${req.url}`);
  next();
});

// Endpoints
app.get('/api/stores', (req, res) => {
  res.json(mockData.handleGetStores());
});

app.get('/api/sales', (req, res) => {
  // Extract query parameters
  const { startDate, endDate, storeIds, region, storeType } = req.query;
  
  // In a real implementation, these would be used to filter the data
  // For this mock, we're just passing them through to the handler
  const params = { startDate, endDate, storeIds, region, storeType };
  
  res.json(mockData.handleGetSales(params));
});

app.get('/api/inventory', (req, res) => {
  // Extract query parameters
  const { storeIds, region, storeType } = req.query;
  
  // In a real implementation, these would be used to filter the data
  const params = { storeIds, region, storeType };
  
  res.json(mockData.handleGetInventory(params));
});

app.get('/api/stores/:storeId/details', (req, res) => {
  const { storeId } = req.params;
  const storeDetails = mockData.handleGetStoreDetails(storeId);
  
  if (!storeDetails) {
    return res.status(404).json({ error: 'Store not found' });
  }
  
  res.json(storeDetails);
});

app.get('/api/filters', (req, res) => {
  res.json(mockData.handleGetFilters());
});

// Error handling
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Something went wrong!' });
});

// Start the server
app.listen(PORT, () => {
  console.log(`RetailMetrics mock API server running on port ${PORT}`);
  console.log('Available endpoints:');
  console.log('  GET /api/stores');
  console.log('  GET /api/sales');
  console.log('  GET /api/inventory');
  console.log('  GET /api/stores/:storeId/details');
  console.log('  GET /api/filters');
});